github: Revadike
patreon: Revadike
custom: [
    "https://www.paypal.me/Revadike",
    "https://coinrequest.io/request/mBAhcRTlknrpSJZ",
    "https://steamcommunity.com/tradeoffer/new/?partner=82699538&token=V7DQVtra"
]
